
target-y := serial-log
serial-log-source-y := main.c \
					   config.c \
					   serial.c \
					   utils.c 

serial-log-ldflags-y := -lpthread
install-y := serial-log:usr/bin/

include ../Build.mk
